//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.logs = new HashSet<log>();
        }
    
        public int itemID { get; set; }
        public string itemName { get; set; }
    
        public virtual ICollection<log> logs { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
