//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int historyID { get; set; }
        public int itemID { get; set; }
        public int total { get; set; }
        public string description { get; set; }
        public DateTime date { get; set; }
        public string invoicenumber { get; set; }
    
        public virtual item item { get; set; }
    }
}
